using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using OsrsMr.Core.Input;
using OsrsMr.Core.Spatial;
using OsrsMr.Core.Scripting;

namespace OsrsMr.Core.Interaction
{
    /// <summary>
    /// High-level navigation and movement controller (walk tile, follow path, toggle run).
    /// </summary>
    public static class Movement
    {
        private static GameState State => BrainEngine.Instance.State;

        public static bool IsRunning => State.StatusEffects.RunEnabled;
        public static int RunEnergy => State.Player.Energy;

        /// <summary>
        /// Walks directly to the specified world tile by projecting to canvas and clicking.
        /// </summary>
        public static async Task<bool> WalkToAsync(int worldX, int worldY)
        {
            if (State?.Player == null) return false;

            var screenPoint = Viewport.WorldToCanvas(
                worldX, worldY, State.Player.Plane,
                State.Player.WorldX, State.Player.WorldY,
                State.Camera);

            if (!screenPoint.HasValue)
            {
                // Tile is off-screen or out of camera viewport: attempt minimap walk
                return await WalkMinimapAsync(worldX, worldY);
            }

            await Mouse.ClickAsync(screenPoint.Value.X, screenPoint.Value.Y);
            return true;
        }

        /// <summary>
        /// Walks to target tile via minimap compass projection.
        /// Standard OSRS fixed minimap center is at approx (643, 83).
        /// </summary>
        public static async Task<bool> WalkMinimapAsync(int worldX, int worldY)
        {
            if (State?.Player == null) return false;

            int dx = worldX - State.Player.WorldX;
            int dy = worldY - State.Player.WorldY;

            // Minimap scale: ~4 pixels per world tile
            int minimapCenterX = 643;
            int minimapCenterY = 83;

            int targetX = minimapCenterX + (dx * 4);
            int targetY = minimapCenterY - (dy * 4); // Y is inverted in 2D screen

            // Clamp within circular minimap radius (~70px)
            int distSq = (targetX - minimapCenterX) * (targetX - minimapCenterX) + (targetY - minimapCenterY) * (targetY - minimapCenterY);
            if (distSq > 70 * 70)
            {
                double angle = Math.Atan2(targetY - minimapCenterY, targetX - minimapCenterX);
                targetX = minimapCenterX + (int)(65 * Math.Cos(angle));
                targetY = minimapCenterY + (int)(65 * Math.Sin(angle));
            }

            await Mouse.ClickAsync(targetX, targetY);
            return true;
        }

        /// <summary>
        /// Follows a list of path waypoints generated by Pathfinder.
        /// </summary>
        public static async Task<bool> WalkPathAsync(IEnumerable<WorldPoint> path)
        {
            if (path == null || State?.Player == null) return false;

            foreach (var pt in path)
            {
                await WalkToAsync(pt.X, pt.Y);
                // Wait until we reach near the waypoint before clicking next
                await Condition.WaitAsync(() =>
                {
                    int dist = Math.Max(Math.Abs(State.Player.WorldX - pt.X), Math.Abs(State.Player.WorldY - pt.Y));
                    return dist <= 3;
                }, timeoutMs: 5000, pollIntervalMs: 150);
            }

            return true;
        }

        /// <summary>
        /// Toggles run energy if below threshold or enabled.
        /// Standard run orb position: approx (577, 127).
        /// </summary>
        public static async Task<bool> ToggleRunAsync(bool enable)
        {
            if (IsRunning == enable) return true;

            await Mouse.ClickAsync(577, 127);
            await Condition.SleepAsync(200, 400);
            return IsRunning == enable;
        }
    }
}
